### ISSUE TITLE
Magento 2 installing get error

### ISSUE THREAD

**Issue by paresh40407** [sashas777/magento-docker#1]
Hi @sashas777 ,

When we install Magento 2.4.4 using docker as the local environment - we have got an error in Magento 2

Run Command: 
composer --ignore-platform-reqs create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .

Error As below:
.....
 - Installing phpmd/phpmd (2.12.0): Extracting archive
  - Installing sebastian/phpcpd (6.0.3): Extracting archive
 236/478 [=============>--------------]  49%    Install of rector/rector failed

Can you please guide us?

**Comment by sashas777** [comment]
Hi @paresh40407 
Why do you use ` --ignore-platform-reqs ` ? 
Is there any error information after this message?

**Comment by paresh40407** [comment]
Hi @sashas777 ,

As per your guidelines, we used the below command:

composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition .

Got same error i.e 236/478 [=============>--------------] 49% Install of rector/rector failed

So, please help me, how i can resolve it?

For --ignore-platform-reqs is the purpose to ignore platform requirements, however, it did not work in my case.

Thanks

**Comment by sashas777** [comment]
@paresh40407 
I tried the same with brand new docker-compose files and Magento did install successfully.  
Can you share your docker-compose files: .env, global.env, and docker-compose.yml? 
What OS do you use?

**Comment by sashas777** [comment]
@paresh40407  I closing this issue because there is no response.
